on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      
      - name: Checkout build_tools repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          ref: master
          path: build_tools
      
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT_2=123" >> $GITHUB_ENV
      - name: Test1
        run: echo $GITHUB_SHA_SHORT_2
      - name: Test2
        run: echo ${{ env.GITHUB_SHA_SHORT_2 }}
