on:
  push:
    branches: '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      
      - name: Checkout build_tools repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          ref: master
          path: build_tools
          fetch-depth: 0
      
      - name: Set env
        run: |
          release_branches=$(git -C build_tools branch -r | grep -o 'origin/release[^ ]*' | sed 's|origin/||' | paste -sd "," -)
          hotfix_branches=$(git -C build_tools branch -r | grep -o 'origin/hotfix[^ ]*' | sed 's|origin/||' | paste -sd "," -)

          echo "release=$release_branches" >> $GITHUB_ENV
          echo "hotfix=$hotfix_branches" >> $GITHUB_ENV

          echo "$release_branches"
          echo "_________________"
          echo "$hotfix_branches"

      
      - name: Test1
        run: echo $release
      - name: Test2
        run: echo $hotfix
