on:
  push:
    branches: '**'

defaults:
  run:
    shell: bash
    working-directory: ./Dep.Tests/puppeteer/engine
    
jobs:
  puppeteer-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Dep.tests
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE-QA/Dep.Tests
          token: ${{ secrets.READ_PAT }}
          path: Dep.Tests
          ref: master

      - name: Set submodule pat token
        run: git config --global url."https://${{ secrets.READ_PAT }}:@github.com/".insteadOf "https://github.com/"
        
      - name: Update submodules
        working-directory: ./Dep.Tests
        run: git submodule update --init puppeteer/files
          
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Prepare env
        run: python install.py
