on:
  push:
    branches: '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      
      - name: Checkout build_tools repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          ref: master
          path: build_tools
          fetch-depth: 0
      
      - name: Set env
        run: |
          branches=$(git branch -r | grep -E 'origin/(release/v|hotfix/v)' | sed 's|origin/||' | paste -sd "," -)

          echo "branches=$branches" >> $GITHUB_ENV

          echo "$branches"

      
      - name: Test1
        run: echo $branches
      - name: Test2
        run: echo $hotfix
