on:
  push:
    branches: '**'

defaults:
  run:
    working-directory: ./Dep.Tests/puppeteer/engine
    
jobs:
  puppeteer-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Dep.tests
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE-QA/Dep.Tests
          token: ${{ secrets.READ_PAT }}
          path: Dep.Tests
          ref: master

      - name: Set submodule pat token
        run: git config --global url."https://${{ secrets.READ_PAT }}:@git.onlyoffice.com/".insteadOf "https://git.onlyoffice.com/"

      - name: Update submodules
        working-directory: ./Dep.Tests
        run: git submodule update --init puppeteer/files

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          install-dependencies: true
          install-chromedriver: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Prepare env
        run: |
          sudo ln -s ${{ steps.setup-chrome.outputs.chrome-path }} /usr/bin/google-chrome-stable
          npm install

      - name: Run puppeteer
        run: |
          # Run tests
          python run.py config_chrome_linux.json
